### PR TITLE
Rename Terraform workflow

### PR DESCRIPTION
**Pull request by bendrucker**
Renames Terraform workflow. The primary display context for these names is here:

Screen Shot 2022-04-06 at 10 39 53

My desired name is `Terraform / check / fmt`, since `Terraform Checks / check` is duplicative. 

In theory we could introduce a `workspace` job and have `Terraform / workspace / *`, though I'm not sure that's a good idea. Workspaces would need to be disabled by default, either via `if` or commented out. The upside of individual workflows is that we can offer individual templates that can be discovered/enabled via the Actions UI. We might consider conditionally managing workspaces based on a file in the repo though. Setting the working directory correctly for repos that put config in `terraform/` has been a problem, discovery might help. If a backend is configured, that's probably a good signal to create workspaces.

An interesting benefit would be that we'd gain the ability to create dependencies between Terraform workflows via `needs`. For example, requiring the `check` job pass before workspace creation is attempted.

### CODE REVIEW

**Review by ryanwholey — APPROVED** [review]

**Comment by ryanwholey** [comment]
Up to this point workspace creation has been a distinct action, as you say probably in part due to being able to create the workflow via Actions UI. Moving towards a job in a single workflow under the Terraform workspace name is interesting... you don't get any plan on your Terraform resources until the workspace is created. So then the `Terraform /check / *` step would be validating your resources, but no human readable plan on any resources, so I think we'd most likely be checking against a skeleton repo.

As mentioned, this could lead to managing the workspace from other inputs (presence of a backend, or a config file). One inconvenience about using a non action/workflow here would be the copy/paste foot-gun. We can default workspace names to the repo easily in GitHub workflows, but if this value is sourced from a backend block or a config file and if you copy values from another repo and forget to change the workspace name, the workspace will plan ok but fail on apply. Not the end of the world obviously, maybe we put some logic into the job to say, hey, your proposed backend does not match the repo name, give me an override boolean that this is okay. 

Additionally, supporting different working directories for different workspaces within the same repo adds some complication. We currently only do this in airflow, but of course 0, 1, many rules applies so we'd want to handle this case.

**Comment by bendrucker** [comment]
Also FWIW we can roll out with the workspace portion commented out in the template, or disabled via a condition/input. Then work on the quirks of auto-discovery of workspace config.

**Comment by bendrucker** [comment]
The immediate question is whether the single workflow is a good idea and creates opportunities for further integration/coupling in the future or just a hazard.

> no human readable plan on any resources, so I think we'd most likely be checking against a skeleton repo

This isn't strictly true. A plan is most useful when you have state. With no state, the plan just spells out all the resources as additions, with many attributes remaining unknown until apply. In cases where chunks of initial config is copied from elsewhere orchestrating the two jobs together ensures that workspaces aren't created with failing config.

In some cases it'll surely be minimal boilerplate but that's not so bad either, at least we know there's valid TF config for the workspace, even if it's empty of actual content.

**Comment by ryanwholey** [comment]
True that the plan is mostly useful when you have state, I guess I'm just used to looking at it.

How does validation handle remote_state references? Let's say we update source but forget to update a dependent, would validation fail blocking workspace updates?

**Comment by bendrucker** [comment]
Validate can only deal with syntax and schema, not any dynamic data. So it knows which `data "terraform_remote_state"` you've defined and that each has an `outputs` attribute that's a map of output name to value, essentially `map(any)`. The actual content of the data source is never fetched until plan time. In this sense, the remote state data source is no different than any other.

**Comment by ryanwholey** [comment]
The only link I see between these two would be if we fully intend to derive the workspace inputs from the terraform configuration in the working directory. As they're configured now, IMO one does not depend on the other. Similarly if we choose to use a config file as inputs for the workspace, I still workspace management as an isolated process to validating the working directory. 

However, moving to API driven and keeping the workspace input process the same, resource management now "needs" both   "check" and "workspace". If we changed the workspace input process to depend on the Terraform working directory config, it would then be 
check -> workspace -> resources

**Comment by ryanwholey** [comment]
Also, of course, the very nice unified namespace "Terraform" on the checks

**Pull request merged**
